export { default as Home_logic } from './Home/Home_logic'
export { default as Contact } from './Contact/Contact'
export { default as Members } from './Members/Members'
export { default as Orders } from './Orders/Orders'
export { default as Reservations } from './Reservations/Reservations'